language: java

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jdk:
  -openjdk11
  
jobs:
  include:
    - stage: build 
      script:
        - cd taxi-mask-backend
        - mvn package -Dmaven.test.skip=true  
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: my_file.txt
        retention-days: 5
      
  
  
notifications:
  email: ekpkomi@gmail.com
  
