language: java

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jdk:
  -openjdk11
  
jobs:
  include:
    - stage: build 
      script:
        - cd taxi-mask-backend
        - mvn package -Dmaven.test.skip=true  
      artifacts:
        paths:
          - taxi-mask-backend/target/taxi-mask-backend-1.0-SNAPSHOT.jar
        expire_in: 1 week
  
  
notifications:
  email: ekpkomi@gmail.com
  
