language: java

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]


services:
  - docker
jdk:
  - openjdk11
#before_install:
#  - mvn -B versions:set -DnewVersion=$TRAVIS_BRANCH -DprocessAllModules -DgenerateBackupPoms=false
script:
  - cd taxi-mask-backend
  - mvn package 
deploy:
  - provider: script
    skip_cleanup: true
    script:
      docker build -t 092837465/taxi-mask-backend:latest taxi-mask-backend && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      && docker push 092837465/taxi-mask-backend:latest
    
  
  
  
