language: java

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jdk:
  -openjdk11
  
jobs:
  include:
    - stage: build 
      image: maven
      script:
        - cd taxi-mask-backend
        - mvn package -Dmaven.test.skip=true  
      artifacts:
        paths:
          - taxi-mask-backend/target/taxi-mask-backend-1.0-SNAPSHOT.jar
        expire_in: 1 week

    - stage: deploy
      image: docker 
      script:
        - cd taxi-mask-backend && docker build -t taximask-java .
        - docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        - docker tag taximask-java:latest 092837465/taximask-java:latest
        - docker push 092837465/taximask-java:latest

  
notifications:
#  email: ekpkomi@gmail.com
  
