language: java

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jdk:
  -openjdk8
script: 
  - cd taxi-mask-backend
  - mvn clean install
notifications:
  email: ekpkomi@gmail.com
  
