# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

stages:
  - build 
  - deploy


 
services:
  - docker:19.03.12-dind  

build:
  stage: package
  image: maven
  script:
    - cd taxi-mask-backend
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - taxi-mask-backend/target/taxi-mask-backend-1.0-SNAPSHOT.jar
    expire_in: 1 week

deploy:
  stage: deploy
  image: docker 
  script:
    - cd taxi-mask-backend && docker build -t testgit-java .
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    - docker tag testgit-java:latest 092837465/testgit-java:latest
    - docker push 092837465/testgit-java:latest
   


